version: "2"
services:
    miniapp:
        image: python:3.10
        ports:
            - 2536:2536
        volumes:
            - .:/var/miniapp/
        working_dir: /var/miniapp/
        command: bash -c "pip install -r server/requirements.txt &>/dev/null && python server/server.py --host 0.0.0.0"

    httpd:
        image: httpd:latest
        ports:
            - 2537:80
        volumes:
            - ./server/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./client/:/usr/local/apache2/htdocs/
